steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg', 'NEXT_PUBLIC_MARZ_VIDEO_MODE=true',
         '--build-arg', 'NEXT_PUBLIC_NEURAL_CORE_URL=${_NEXT_PUBLIC_NEURAL_CORE_URL}',
         '--build-arg', 'NEXT_PUBLIC_GCP_ORCHESTRATOR_WAKE_URL=${_NEXT_PUBLIC_GCP_ORCHESTRATOR_WAKE_URL}',
         '--build-arg', 'NEXT_PUBLIC_GCP_ORCHESTRATOR_WAKE_TOKEN=${_NEXT_PUBLIC_GCP_ORCHESTRATOR_WAKE_TOKEN}',
         '--build-arg', 'NEXT_PUBLIC_VAPID_PUBLIC_KEY=${_NEXT_PUBLIC_VAPID_PUBLIC_KEY}',
         '--build-arg', 'NEXT_PUBLIC_METRICS_URL=${_NEXT_PUBLIC_METRICS_URL}',
         '--build-arg', 'NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}',
         '--build-arg', 'HUGGINGFACE_TOKEN=${_HUGGINGFACE_TOKEN}',
         '--build-arg', 'HF_TOKEN=${_HUGGINGFACE_TOKEN}',
         '--build-arg', 'HUGGINGFACE_HUB_TOKEN=${_HUGGINGFACE_TOKEN}',
         '-t', 'gcr.io/$PROJECT_ID/opsvantage-ai-builder', '.']

# Push the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/opsvantage-ai-builder']

# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'opsvantage-ai-builder',
         '--image', 'gcr.io/$PROJECT_ID/opsvantage-ai-builder',
         '--region', 'europe-west4',
         '--platform', 'managed',
         '--allow-unauthenticated',
         '--min-instances', '0',
         '--max-instances', '6',
         '--set-env-vars', 'NEXT_PUBLIC_MARZ_VIDEO_MODE=true,NEXT_PUBLIC_NEURAL_CORE_URL=${_NEXT_PUBLIC_NEURAL_CORE_URL},NEXT_PUBLIC_GCP_ORCHESTRATOR_WAKE_URL=${_NEXT_PUBLIC_GCP_ORCHESTRATOR_WAKE_URL},NEXT_PUBLIC_GCP_ORCHESTRATOR_WAKE_TOKEN=${_NEXT_PUBLIC_GCP_ORCHESTRATOR_WAKE_TOKEN},NEXT_PUBLIC_VAPID_PUBLIC_KEY=${_NEXT_PUBLIC_VAPID_PUBLIC_KEY},NEXT_PUBLIC_METRICS_URL=${_NEXT_PUBLIC_METRICS_URL}',
         '--set-secrets', 'DATABASE_URL=${_DATABASE_URL_SECRET}:latest,SOVEREIGN_PASSWORD=${_SOVEREIGN_PASSWORD_SECRET}:latest,PUSH_SERVICE_TOKEN=${_PUSH_SERVICE_TOKEN_SECRET}:latest,VAPID_PRIVATE_KEY=${_VAPID_PRIVATE_KEY_SECRET}:latest,VAPID_SUBJECT=${_VAPID_SUBJECT_SECRET}:latest,NEXTAUTH_SECRET=${_NEXTAUTH_SECRET_SECRET}:latest,HUGGINGFACE_TOKEN=${_HUGGINGFACE_TOKEN_SECRET}:latest,HF_TOKEN=${_HUGGINGFACE_TOKEN_SECRET}:latest,HUGGINGFACE_HUB_TOKEN=${_HUGGINGFACE_TOKEN_SECRET}:latest,GEMINI_API_KEY=${_GEMINI_API_KEY_SECRET}:latest',
         '--port', '8080',
         '--memory', '1Gi',
         '--cpu', '1']

# Cleanup old container images (best-effort) to keep registry storage low.
# Runs only after successful build+deploy because Cloud Build stops on earlier failures.
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -euo pipefail

      # Cleanup is intentionally optional. During forced deploys we want fast builds,
      # and registry cleanup can take long enough to hit Cloud Build timeouts.
      if [ "${_RUN_REGISTRY_CLEANUP}" != "true" ]; then
        echo "[cleanup] skipping (set _RUN_REGISTRY_CLEANUP=true to enable)"
        exit 0
      fi

      echo "[cleanup] Removing images older than 24h from Container Registry (gcr.io)"
      cutoff="$(date -u -d '24 hours ago' +%Y-%m-%dT%H:%M:%SZ)"
      for repo in "gcr.io/$PROJECT_ID/opsvantage-ai-builder" "gcr.io/$PROJECT_ID/marz-neural-core"; do
        echo "[cleanup] repo=${repo} cutoff=${cutoff}"
        # list digests older than cutoff
        digests="$(gcloud container images list-tags "${repo}" --format='value(digest,timestamp.datetime)' --limit=999999 2>/dev/null | awk -v c="${cutoff}" '$2!="" && $2 < c {print $1}' | sort -u || true)"
        if [ -z "${digests}" ]; then
          echo "[cleanup] no digests to delete for ${repo}"
          continue
        fi
        deleted=0
        while read -r digest; do
          if [ -z "${digest}" ]; then
            continue
          fi

          # list-tags returns digests without the sha256: prefix in some environments.
          # Normalize to the required form: sha256:<digest>
          if [[ "${digest}" == sha256:* ]]; then
            normalized="${digest}"
          else
            normalized="sha256:${digest}"
          fi

          if [ -z "${normalized}" ]; then
            continue
          fi

          echo "[cleanup] deleting ${repo}@${normalized}"
          gcloud container images delete "${repo}@${normalized}" --force-delete-tags --quiet || true

          deleted=$((deleted + 1))
          if [ "${deleted}" -ge 25 ]; then
            echo "[cleanup] reached deletion cap (25) for ${repo}; stopping early"
            break
          fi
        done <<< "${digests}"
      done

images:
- 'gcr.io/$PROJECT_ID/opsvantage-ai-builder'

substitutions:
  _NEXT_PUBLIC_NEURAL_CORE_URL: 'https://marz-neural-core-1018462465472.europe-west4.run.app'
  _NEXT_PUBLIC_GCP_ORCHESTRATOR_WAKE_URL: ''
  _NEXT_PUBLIC_GCP_ORCHESTRATOR_WAKE_TOKEN: ''
  _NEXT_PUBLIC_VAPID_PUBLIC_KEY: 'BBB9aV3pwuYlwNSk-KlYchgyBkxXVfOD76rMaeNK9xaP62DN_2PTIRhjTTeCXF3E1pR2wcV50RAhe4od2HFiDsE'
  _NEXT_PUBLIC_METRICS_URL: 'https://opsvantage-ai-builder-1018462465472.europe-west4.run.app/api/metrics/vitals'
  _NEXTAUTH_SECRET: ''
  _HUGGINGFACE_TOKEN: ''
  _SOVEREIGN_PASSWORD_SECRET: 'SOVEREIGN_PASSWORD'
  _PUSH_SERVICE_TOKEN_SECRET: 'PUSH_SERVICE_TOKEN'
  _VAPID_PRIVATE_KEY_SECRET: 'VAPID_PRIVATE_KEY'
  _VAPID_SUBJECT_SECRET: 'VAPID_SUBJECT'
  _NEXTAUTH_SECRET_SECRET: 'NEXTAUTH_SECRET'
  _DATABASE_URL_SECRET: 'DATABASE_URL'
  _HUGGINGFACE_TOKEN_SECRET: 'HUGGINGFACE_TOKEN'
  _GEMINI_API_KEY_SECRET: 'GEMINI_API_KEY'
  _RUN_REGISTRY_CLEANUP: 'false'

timeout: '1600s'
