steps:
# Install dependencies
- name: 'node:20'
  entrypoint: 'npm'
  args: ['install', '--legacy-peer-deps']

# Run tests
- name: 'node:20'
  entrypoint: 'npm'
  args: ['test']

# Build the application
- name: 'node:20'
  entrypoint: 'npm'
  args: ['run', 'build']

# Deploy to Google Cloud Run (optional)
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/opsvantage-ai-builder', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/opsvantage-ai-builder']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'opsvantage-ai-builder'
  - '--image=gcr.io/$PROJECT_ID/opsvantage-ai-builder'
  - '--region=us-central1'
  - '--platform=managed'
  - '--allow-unauthenticated'

options:
  env:
    - 'NODE_ENV=production'
  volumes:
  - name: 'npm-cache'
    path: '/root/.npm'

timeout: '1600s'