steps:
# Install dependencies
- name: 'node:20'
  entrypoint: 'npm'
  args: ['install']

# Build the application
- name: 'node:20'
  entrypoint: 'npm'
  args: ['run', 'build']

# Build container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/opsvantage-ai-builder', '.']

# Push container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/opsvantage-ai-builder']

# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'opsvantage-ai-builder', 
         '--image', 'gcr.io/$PROJECT_ID/opsvantage-ai-builder',
         '--region', 'us-central1',
         '--platform', 'managed',
         '--allow-unauthenticated']

options:
  env:
    - 'NODE_ENV=production'

timeout: '1600s'