// Placeholder for a real Gemini client
// In a real app, this would use the Google AI SDK
// e.g., import { GoogleGenerativeAI } from "@google/generative-ai";

export async function getGenerativeModel(modelName: string = 'gemini-pro') {
  // const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);
  // return genAI.getGenerativeModel({ model: modelName });

  // Mock implementation for now
  return {
    generateContent: async (prompt: string): Promise<{ response: { text: () => string } }> => {
      console.log('--- MOCK GEMINI PROMPT ---');
      console.log(prompt.substring(0, 500) + '...');
      console.log('--------------------------');

      // Simulate network delay
      await new Promise(resolve => setTimeout(resolve, 1500));

      if (prompt.includes('generate a sitemap')) {
        const mockSitemap = [
          { title: 'Home', slug: '/', type: 'HOME', isHome: true },
          { title: 'About Us', slug: '/about', type: 'CUSTOM', isHome: false },
          { title: 'Services', slug: '/services', type: 'CUSTOM', isHome: false },
          { title: 'Contact Us', slug: '/contact', type: 'CUSTOM', isHome: false },
        ];
        return {
          response: { text: () => `\`\`\`json\n${JSON.stringify(mockSitemap, null, 2)}\n\`\`\`` },
        };
      }

      if (prompt.includes('generate the content for a webpage')) {
        const mockPageData = {
          seoTitle: "Mock SEO Title for the Page",
          seoDescription: "This is a mock SEO-optimized meta description, designed to be around 155 characters to fit best practices for search engine results pages.",
          sections: [
            {
              type: 'HERO',
              variant: 'default',
              data: {
                headline: 'Dynamic Headline Generated by AI',
                subheadline: 'A compelling subheadline that grabs user attention and drives conversion.',
                cta: { text: 'Learn More', link: '/about' },
              },
            },
          ],
        };
        return {
          response: { text: () => `\`\`\`json\n${JSON.stringify(mockPageData, null, 2)}\n\`\`\`` },
        };
      }

      // Fallback for unknown prompts
      return { response: { text: () => '```json\n{}\n```' } };
    },
  };
}