steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/marz-neural-core:$BUILD_ID', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/marz-neural-core:$BUILD_ID']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    [
      'run', 'deploy', 'marz-neural-core',
      '--image', 'gcr.io/$PROJECT_ID/marz-neural-core:$BUILD_ID',
      '--region', '${_NEURAL_CORE_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--execution-environment', 'gen2',
      '--cpu', '8',
      '--memory', '32Gi',
      '--gpu', '1',
      '--gpu-type', '${_GPU_TYPE}',
      '--concurrency', '10',
      '--min-instances', '0',
      '--max-instances', '1',
      '--port', '8080',
      '--set-env-vars', 'CONSTITUTION_PATH=${_CONSTITUTION_PATH},VECTOR_STORE_PATH=${_VECTOR_STORE_PATH},PUSH_SERVICE_URL=${_PUSH_SERVICE_URL},NEURAL_MODEL_ID=${_NEURAL_MODEL_ID},NEURAL_USE_VLLM=false,COQUI_TOS_AGREED=1,WAV2LIP_CHECKPOINT_URL=${_WAV2LIP_CHECKPOINT_URL},PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128,MARZ_MAX_AUDIO_SECONDS=22,MARZ_MAX_AVATAR_MB=150',
      '--set-secrets', 'MEMORY_VAULT_URL=${_MEMORY_VAULT_URL_SECRET}:latest,TAVILY_API_KEY=${_TAVILY_API_KEY_SECRET}:latest,PUSH_SERVICE_TOKEN=${_PUSH_SERVICE_TOKEN_SECRET}:latest,HUGGINGFACE_TOKEN=${_HUGGINGFACE_TOKEN_SECRET}:latest,HF_TOKEN=${_HUGGINGFACE_TOKEN_SECRET}:latest,HUGGINGFACE_HUB_TOKEN=${_HUGGINGFACE_TOKEN_SECRET}:latest',
    ]

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    [
      'run', 'jobs', 'deploy', 'marz-reflection-engine',
      '--image', 'gcr.io/$PROJECT_ID/marz-neural-core:$BUILD_ID',
      '--region', '${_NEURAL_CORE_REGION}',
      '--tasks', '1',
      '--max-retries', '1',
      '--task-timeout', '900s',
      '--command', 'python',
      '--args', 'reflection_engine.py',
      '--set-env-vars', 'CONSTITUTION_PATH=${_CONSTITUTION_PATH},VECTOR_STORE_PATH=${_VECTOR_STORE_PATH},PUSH_SERVICE_URL=${_PUSH_SERVICE_URL},NEURAL_MODEL_ID=${_NEURAL_MODEL_ID},NEURAL_USE_VLLM=false,COQUI_TOS_AGREED=1,WAV2LIP_CHECKPOINT_URL=${_WAV2LIP_CHECKPOINT_URL},PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128,MARZ_MAX_AUDIO_SECONDS=22,MARZ_MAX_AVATAR_MB=150',
      '--set-secrets', 'MEMORY_VAULT_URL=${_MEMORY_VAULT_URL_SECRET}:latest,TAVILY_API_KEY=${_TAVILY_API_KEY_SECRET}:latest,PUSH_SERVICE_TOKEN=${_PUSH_SERVICE_TOKEN_SECRET}:latest,HUGGINGFACE_TOKEN=${_HUGGINGFACE_TOKEN_SECRET}:latest,HF_TOKEN=${_HUGGINGFACE_TOKEN_SECRET}:latest,HUGGINGFACE_HUB_TOKEN=${_HUGGINGFACE_TOKEN_SECRET}:latest',
    ]

images:
- 'gcr.io/$PROJECT_ID/marz-neural-core:$BUILD_ID'

substitutions:
  _NEURAL_CORE_REGION: 'europe-west4'
  _GPU_TYPE: 'nvidia-l4'
  _NEURAL_MODEL_ID: 'microsoft/Phi-3-mini-4k-instruct'
  _CONSTITUTION_PATH: '/workspace/neural-core/constitution.md'
  _MEMORY_VAULT_URL_SECRET: 'MEMORY_VAULT_URL'
  _VECTOR_STORE_PATH: '/workspace/neural-core/data/chroma'
  _TAVILY_API_KEY_SECRET: 'TAVILY_API_KEY'
  _PUSH_SERVICE_URL: 'https://opsvantage-ai-builder-1018462465472.europe-west4.run.app/api/marz/push/dispatch'
  _PUSH_SERVICE_TOKEN_SECRET: 'PUSH_SERVICE_TOKEN'
  _HUGGINGFACE_TOKEN_SECRET: 'HUGGINGFACE_TOKEN'
  _WAV2LIP_CHECKPOINT_URL: 'gs://opsvantage-artifacts/checkpoints/wav2lip_gan.pth'

timeout: '3600s'
